--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    mensaje character varying(255),
    telefono_contacto character varying(20) NOT NULL,
    fecha_hora timestamp(6) without time zone
);


ALTER TABLE public.notificaciones OWNER TO appuser;

--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: appuser
--

COPY public.notificaciones (id, mensaje, telefono_contacto, fecha_hora) FROM stdin;
\.


--
-- Name: notificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: appuser
--

SELECT pg_catalog.setval('public.notificaciones_id_seq', 1, false);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);

-- DATA
INSERT INTO public.notificaciones (mensaje, telefono_contacto, fecha_hora) VALUES 
('Su coche está listo para ser recogido.', '3512044273', TIMESTAMP '2023-09-20 10:20:00'),
('Recordatorio: su cita de mantenimiento es mañana a las 10 AM.', '3512044273', TIMESTAMP '2023-09-20 10:20:00'),
('Oferta especial: 20% de descuento en servicios de reparación este mes.', '3512044273', TIMESTAMP '2023-09-20 10:20:00');




--
-- PostgreSQL database dump complete
--

