FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY pom.xml .
COPY mvnw .
COPY mvnw.cmd .
COPY .mvn .mvn


#COPY target/*.jar app.jar
COPY src ./src

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests


EXPOSE 8083

#ENTRYPOINT ["java", "-jar", "app.jar"]
#ENTRYPOINT [ "./mvnw", "spring-boot:run"]
CMD ["./mvnw", "spring-boot:run"]
