FROM keycloak/keycloak:26.4.7

WORKDIR /opt/keycloak

COPY ./carsellingrealm-realm.json .

EXPOSE 8080

ENV KC_BOOTSTRAP_ADMIN_USERNAME=admin
ENV KC_BOOTSTRAP_ADMIN_PASSWORD=admin

RUN ["./bin/kc.sh", "import" , "--file", "./carsellingrealm-realm.json"]
RUN ["./bin/kc.sh", "bootstrap-admin", "user", "--username", "$KC_BOOTSTRAP_ADMIN_USERNAME", "--password:env", "KC_BOOTSTRAP_ADMIN_PASSWORD"]

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev"]
